# fly.toml app configuration file generated for fh-server on 2023-11-17T19:57:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fh-server"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
